#!/bin/ksh
#PBS -S /usr/bin/ksh
#PBS -q np
#PBS -N LES_3
#PBS -m a
#PBS -l walltime=24:10:00

#PBS -l EC_total_tasks=96
#PBS -l EC_threads_per_task=1
#PBS -l EC_memory_per_task=1GB
#PBS -l EC_hyperthreads=1

prgenvswitchto intel
module load netcdf4

cd /nobackup/users/stratum/KNMI_testbed/cases/cabauw_aug2018/cabauwNBL_20160804_20160818_alpha_z0/20160805

aprun -n 96 ./dales4 namoptions.002 > dales4.out