#!/bin/ksh
#PBS -S /usr/bin/ksh
#PBS -q np
#PBS -N LES_CB_15
#PBS -m a
#PBS -l walltime=24:10:00

#PBS -l EC_total_tasks=96
#PBS -l EC_threads_per_task=1
#PBS -l EC_memory_per_task=1GB
#PBS -l EC_hyperthreads=1

prgenvswitchto intel
module load netcdf4

# Switch to working directory
cd /scratch/ms/nl/nkbs/DALES/KNMI_testbed/cabauw_20160804_20160818//20160818

aprun -n 96 ./dales4 namoptions.001 > dales4.out
